/**
 * Pizza Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngredientDto } from './ingredientDto';


export interface PizzaDto { 
    pizza_id: number;
    name?: string;
    pizza_dough_type?: string;
    is_calzone: boolean;
    ingredients?: Array<IngredientDto>;
}

